### PR TITLE
Correct mistake in CS0523

### PR DESCRIPTION
**Pull request by Rageking8**
## Summary

Fix some errors introduced in #37990.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/csharp/language-reference/compiler-messages/cs0523.md](https://github.com/dotnet/docs/blob/21aeefd252c7f64aa0b1f8cb294f731413217be0/docs/csharp/language-reference/compiler-messages/cs0523.md) | [Compiler Error CS0523](https://review.learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0523?branch=pr-en-us-38840) |

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
Thanks @Rageking8 

This LGTM, and I'll :shipit: now.
