### ISSUE TITLE
No info about ref extension methods

### ISSUE THREAD

**Issue by taquion87** [dotnet/docs#13877]
There is no info here about the new feature regarding ref extension methods for structs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f86ebf5-b5c0-324a-43df-c17015729d01
* Version Independent ID: 8ce4ad4a-3dbd-42dc-bae3-230900097299
* Content: [What's new in C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#feedback)
* Content Source: [docs/csharp/whats-new/csharp-7-2.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-2.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
According to my tests, this feature is available in C# 7.0 (It's not mentioned in that article either, so scheduling this for October).

**Comment by svick** [comment]
@BillWagner When I compile the following code with `<LangVersion>7.0</LangVersion>`:

```c#
struct S {}

static class Extensions
{
    static void M(ref this S s) {}
}
```

I get the error:

> error CS8107: Feature 'ref extension methods' is not available in C# 7.0. Please use language version 7.2 or greater.

So I don't think it's a C# 7.0 feature.

**Comment by BillWagner** [comment]
@svick  Thanks for checking. I tried the same thing on a preview build and it worked. I'll check again.

**Comment by taquion87** [comment]
@BillWagner, it compiles in 7.0 if you change the order of the method parameter modifiers. But if you want to consume the extension method you get a compile error:

> error CS8107: Feature 'ref extension methods' is not available in C# 7.0. Please use language version 7.2 or greater.

So, the only way to use the extension method is as a static helper method:
```
var s = new S();
Extensions.M(ref s);
```

**Comment by svick** [comment]
I thought this odd behavior was worth reporting to Roslyn, so I did so: https://github.com/dotnet/roslyn/issues/38486.
