### ISSUE TITLE
[Breaking change]: System.Windows.Extensions package no longer references System.Drawing.Common

### ISSUE THREAD

**Issue by ericstj** [dotnet/docs#37525]
### Description

The `System.Windows.Extensions` package no longer references the `System.Drawing.Common` package.

### Version

.NET 8 Preview 7

### Previous behavior

The `System.Windows.Extensions` package referenced the `System.Drawing.Common` package.

### New behavior

The `System.Windows.Extensions` package no longer references the `System.Drawing.Common` package.  If you depended on this package reference bringing in `System.Drawing.Common` it will no longer do so.

You may see a compilation error like:
```
error CS1069: The type name 'FontConverter' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.
```
Or complaints of other missing types in System.Drawing.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

This avoids a dependency on `System.Drawing.Common` when `System.Windows.Extensions` is referenced.

This will help more components remove a dependency on `System.Drawing.Common` unless they actually need it.  See https://github.com/dotnet/msbuild/issues/8962.

### Recommended action

If you still need to use `System.Drawing.Common` add a direct reference.

### Feature area

Windows Forms

---
[Associated WorkItem - 177288](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177288)

**Comment by ericstj** [comment]
Change introduced in https://github.com/dotnet/runtime/pull/88157
